DELETE http://localhost:3003/api/blogs/64cd47ba7d4f9ea860d6c834
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVuem9WSCIsImlkIjoiNjRiMmE0MzM0ZGNhOTdhYTcyNjZjOGIzIiwiaWF0IjoxNjkxMTc0NjAzfQ.2Bouio-Ook4WAlMqHWOnjyPD2SXXL5uAg7j2J5Np428
